version: '3.2'
services:
#  client:
#    build:
#      context: .
#      dockerfile: client/Dockerfile
#    ports:
#      - "8080:80"
#    depends_on:
#      - server
#    restart: unless-stopped
#    networks:
#      - my_network
#    volumes:
#      - ./client/static:/client/static

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - my_network
    environment:
      - FLASK_ENV=development
    volumes:
      - ./server/db/uploads:/server/db/uploads
      - ./server/api/static:/server/api/static

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=twitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    command: -c logging_collector=on -c log_directory=log/ -c log_destination='stderr' -c log_filename='postgresql-%Y-%m-%d_%H%M%S.log' -c log_statement='all'

networks:
  my_network:
    driver: bridge